apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
spec:
  selector:
    matchLabels:
      app: nginx-hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
      - name: nginx-hello-world
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32042
  selector:
    app: nginx-hello-world
